//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using test.HelperClasses;
using test.FactoryClasses;
using test.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace test.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Instructor'.<br/><br/></summary>
	[Serializable]
	public partial class InstructorEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<CourseEntity> _courses;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static InstructorEntityStaticMetaData _staticMetaData = new InstructorEntityStaticMetaData();
		private static InstructorRelations _relationsFactory = new InstructorRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Courses</summary>
			public static readonly string Courses = "Courses";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class InstructorEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public InstructorEntityStaticMetaData()
			{
				SetEntityCoreInfo("InstructorEntity", InheritanceHierarchyType.None, false, (int)test.EntityType.InstructorEntity, typeof(InstructorEntity), typeof(InstructorEntityFactory), false);
				AddNavigatorMetaData<InstructorEntity, EntityCollection<CourseEntity>>("Courses", a => a._courses, (a, b) => a._courses = b, a => a.Courses, () => new InstructorRelations().CourseEntityUsingInstructorId, typeof(CourseEntity), (int)test.EntityType.CourseEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static InstructorEntity()
		{
		}

		/// <summary> CTor</summary>
		public InstructorEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public InstructorEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this InstructorEntity</param>
		public InstructorEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Instructor which data should be fetched into this Instructor object</param>
		public InstructorEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Instructor which data should be fetched into this Instructor object</param>
		/// <param name="validator">The custom validator object for this InstructorEntity</param>
		public InstructorEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected InstructorEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Course' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCourses() { return CreateRelationInfoForNavigator("Courses"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this InstructorEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static InstructorRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Course' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCourses { get { return _staticMetaData.GetPrefetchPathElement("Courses", CommonEntityBase.CreateEntityCollection<CourseEntity>()); } }

		/// <summary>The Email property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."Email".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)InstructorFieldIndex.Email, true); }
			set	{ SetValue((int)InstructorFieldIndex.Email, value); }
		}

		/// <summary>The FirstName property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."FirstName".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String FirstName
		{
			get { return (System.String)GetValue((int)InstructorFieldIndex.FirstName, true); }
			set	{ SetValue((int)InstructorFieldIndex.FirstName, value); }
		}

		/// <summary>The Id property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."Id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)InstructorFieldIndex.Id, true); }
			set	{ SetValue((int)InstructorFieldIndex.Id, value); }
		}

		/// <summary>The LastName property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."LastName".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String LastName
		{
			get { return (System.String)GetValue((int)InstructorFieldIndex.LastName, true); }
			set	{ SetValue((int)InstructorFieldIndex.LastName, value); }
		}

		/// <summary>The OfficeLocation property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."OfficeLocation".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String OfficeLocation
		{
			get { return (System.String)GetValue((int)InstructorFieldIndex.OfficeLocation, true); }
			set	{ SetValue((int)InstructorFieldIndex.OfficeLocation, value); }
		}

		/// <summary>The Phone property of the Entity Instructor<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Instructor"."Phone".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Phone
		{
			get { return (System.String)GetValue((int)InstructorFieldIndex.Phone, true); }
			set	{ SetValue((int)InstructorFieldIndex.Phone, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CourseEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CourseEntity))]
		public virtual EntityCollection<CourseEntity> Courses { get { return GetOrCreateEntityCollection<CourseEntity, CourseEntityFactory>("Instructor", true, false, ref _courses); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace test
{
	public enum InstructorFieldIndex
	{
		///<summary>Email. </summary>
		Email,
		///<summary>FirstName. </summary>
		FirstName,
		///<summary>Id. </summary>
		Id,
		///<summary>LastName. </summary>
		LastName,
		///<summary>OfficeLocation. </summary>
		OfficeLocation,
		///<summary>Phone. </summary>
		Phone,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace test.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Instructor. </summary>
	public partial class InstructorRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between InstructorEntity and CourseEntity over the 1:n relation they have, using the relation between the fields: Instructor.Id - Course.InstructorId</summary>
		public virtual IEntityRelation CourseEntityUsingInstructorId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Courses", true, new[] { InstructorFields.Id, CourseFields.InstructorId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticInstructorRelations
	{
		internal static readonly IEntityRelation CourseEntityUsingInstructorIdStatic = new InstructorRelations().CourseEntityUsingInstructorId;

		/// <summary>CTor</summary>
		static StaticInstructorRelations() { }
	}
}
