//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using test.FactoryClasses;
using test.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace test.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCourseEntityInfo();
			InitEnrollmentEntityInfo();
			InitInstructorEntityInfo();
			InitStudentEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CourseEntity's info objects</summary>
		private void InitCourseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CourseFieldIndex), "CourseEntity");
			this.AddElementFieldInfo("CourseEntity", "Description", typeof(System.String), false, false, false, true,  (int)CourseFieldIndex.Description, 1073741824, 0, 0);
			this.AddElementFieldInfo("CourseEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)CourseFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CourseEntity", "InstructorId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)CourseFieldIndex.InstructorId, 0, 0, 10);
			this.AddElementFieldInfo("CourseEntity", "Name", typeof(System.String), false, false, false, false,  (int)CourseFieldIndex.Name, 1073741824, 0, 0);
		}

		/// <summary>Inits EnrollmentEntity's info objects</summary>
		private void InitEnrollmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EnrollmentFieldIndex), "EnrollmentEntity");
			this.AddElementFieldInfo("EnrollmentEntity", "CourseId", typeof(System.Int32), false, true, false, false,  (int)EnrollmentFieldIndex.CourseId, 0, 0, 10);
			this.AddElementFieldInfo("EnrollmentEntity", "EnrollmentDate", typeof(System.DateTime), false, false, false, false,  (int)EnrollmentFieldIndex.EnrollmentDate, 0, 0, 0);
			this.AddElementFieldInfo("EnrollmentEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)EnrollmentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("EnrollmentEntity", "StudentId", typeof(System.Int32), false, true, false, false,  (int)EnrollmentFieldIndex.StudentId, 0, 0, 10);
		}

		/// <summary>Inits InstructorEntity's info objects</summary>
		private void InitInstructorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(InstructorFieldIndex), "InstructorEntity");
			this.AddElementFieldInfo("InstructorEntity", "Email", typeof(System.String), false, false, false, false,  (int)InstructorFieldIndex.Email, 1073741824, 0, 0);
			this.AddElementFieldInfo("InstructorEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)InstructorFieldIndex.FirstName, 1073741824, 0, 0);
			this.AddElementFieldInfo("InstructorEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)InstructorFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("InstructorEntity", "LastName", typeof(System.String), false, false, false, false,  (int)InstructorFieldIndex.LastName, 1073741824, 0, 0);
			this.AddElementFieldInfo("InstructorEntity", "OfficeLocation", typeof(System.String), false, false, false, true,  (int)InstructorFieldIndex.OfficeLocation, 1073741824, 0, 0);
			this.AddElementFieldInfo("InstructorEntity", "Phone", typeof(System.String), false, false, false, true,  (int)InstructorFieldIndex.Phone, 1073741824, 0, 0);
		}

		/// <summary>Inits StudentEntity's info objects</summary>
		private void InitStudentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(StudentFieldIndex), "StudentEntity");
			this.AddElementFieldInfo("StudentEntity", "DateOfBirth", typeof(System.DateTime), false, false, false, false,  (int)StudentFieldIndex.DateOfBirth, 0, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Email", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.Email, 1073741824, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.FirstName, 1073741824, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)StudentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("StudentEntity", "LastName", typeof(System.String), false, false, false, false,  (int)StudentFieldIndex.LastName, 1073741824, 0, 0);
			this.AddElementFieldInfo("StudentEntity", "Phone", typeof(System.String), false, false, false, true,  (int)StudentFieldIndex.Phone, 1073741824, 0, 0);
		}
	}
}