//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace test.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCourseEntityMappings();
			InitEnrollmentEntityMappings();
			InitInstructorEntityMappings();
			InitStudentEntityMappings();
		}

		/// <summary>Inits CourseEntity's mappings</summary>
		private void InitCourseEntityMappings()
		{
			this.AddElementMapping("CourseEntity", @"test", @"public", "Course", 4, 0);
			this.AddElementFieldMapping("CourseEntity", "Description", "Description", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CourseEntity", "Id", "Id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("CourseEntity", "InstructorId", "InstructorId", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("CourseEntity", "Name", "Name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits EnrollmentEntity's mappings</summary>
		private void InitEnrollmentEntityMappings()
		{
			this.AddElementMapping("EnrollmentEntity", @"test", @"public", "Enrollment", 4, 0);
			this.AddElementFieldMapping("EnrollmentEntity", "CourseId", "CourseId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("EnrollmentEntity", "EnrollmentDate", "EnrollmentDate", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("EnrollmentEntity", "Id", "Id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("EnrollmentEntity", "StudentId", "StudentId", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
		}

		/// <summary>Inits InstructorEntity's mappings</summary>
		private void InitInstructorEntityMappings()
		{
			this.AddElementMapping("InstructorEntity", @"test", @"public", "Instructor", 6, 0);
			this.AddElementFieldMapping("InstructorEntity", "Email", "Email", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("InstructorEntity", "FirstName", "FirstName", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("InstructorEntity", "Id", "Id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("InstructorEntity", "LastName", "LastName", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("InstructorEntity", "OfficeLocation", "OfficeLocation", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("InstructorEntity", "Phone", "Phone", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits StudentEntity's mappings</summary>
		private void InitStudentEntityMappings()
		{
			this.AddElementMapping("StudentEntity", @"test", @"public", "Student", 6, 0);
			this.AddElementFieldMapping("StudentEntity", "DateOfBirth", "DateOfBirth", false, "Date", 0, 0, 0, false, "", null, typeof(System.DateTime), 0);
			this.AddElementFieldMapping("StudentEntity", "Email", "Email", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("StudentEntity", "FirstName", "FirstName", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("StudentEntity", "Id", "Id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("StudentEntity", "LastName", "LastName", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("StudentEntity", "Phone", "Phone", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
		}

	}
}
